@startuml
'https://plantuml.com/sequence-diagram
'https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow

title Client Credentials Flow


participant "client-app" as client
participant "authorization-server" as idp
participant "resosurce-server" as res_srv

== Get Access Token ==
client -> idp: authenticate with client-id + client-secret to /token
idp -> idp: validate client-id + client-secret
idp -> client: access token

== Fetch Data ==
client -> res_srv: request data with access token
res_srv -> client: response with data

@enduml