@startuml
'https://plantuml.com/sequence-diagram
'https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-proof-key-for-code-exchange-pkce

title Authorization Code Flow with Proof Key for Code Exchange (PKCE) with OIDC

actor "User" as user
participant "client-app" as client
participant "authorization-server" as idp
participant "resource-server" as res_srv

== Get Access Token ==
user -> client: Click login link
client -> client: create code_verifier
client -> idp: redirect to /authorize endpoint
idp -> user: redirect to user login
user -> idp: login and consent
idp -> client: send authorization code
client -> idp: authorization code + code verifier to /token
idp -> idp: validate code verifier and challenge
idp -> client: id token + access token

== Fetch Data ==
client -> res_srv: request data with access token
res_srv -> client: response with data

@enduml
