
server:
  port: 9000

debug: true

redirect:
  server-uris:
    - http://localhost:8080
    - http://localhost:3000

auth-server:
  issuer: 'http://auth-server:9000'

logging:
  level:
    root: info
    org.springframework.security: trace
