
server:
  port: 9000

debug: true

auth-server:
  issuer: 'http://auth-server:9000'

redirect:
  server-uris: |-
    http://localhost:8080/login/oauth2/code/messaging-client-oidc,
    http://localhost:8080/login/oauth2/code/messaging-client-authorization-code,
    http://localhost:8080/authorized,
    http://localhost:3000/login/oauth2/code/messaging-client-oidc,
    http://localhost:3000/login/oauth2/code/messaging-client-authorization-code,
    http://localhost:3000/authorized

logging:
  level:
    root: info
    org.springframework.security: info
